### ISSUE TITLE
Install via composer results in class not found

### ISSUE THREAD

**Issue by MichaelMallett** [opdavies/drupal-vm-generator#34]
Hi,

I get a PHP Fatal error when installing via packagist:
PHP Fatal error:  Class 'DrupalVmGenerator\Application' not found in /Users/Mike/.composer/vendor/opdavies/drupal-vm-config-generator/bin/drupalvm.php on line 13

Fatal error: Class 'DrupalVmGenerator\Application' not found in /Users/Mike/.composer/vendor/opdavies/drupal-vm-config-generator/bin/drupalvm.php on line 13

I also can't remove the package using composer global remove...tbh I'm not sure if there's just something funky going on with my composer because I can't find the class it's after

**Comment by opdavies** [comment]
@MichaelMallett The path to autoload.php was not correct when installing via Composer. I've just tagged 2.4.1 with a fix for this, so if you update now, it should work.
