### ISSUE TITLE
Can't get this to install with current version of drush

### ISSUE THREAD

**Issue by MichaelMallett** [opdavies/drupal-vm-generator#47]
There is a conflict with version numbers of symfony/console with the current version of drush. 

drush requires ~2.7
drupal-vm-generator requires ^3.0

Is there any way to resolve this quickly? Can this package work with symfony console ^2.7?

**Comment by opdavies** [comment]
The tests pass with 2.7 versions of the components, so I've adjusted the composer.json file to include either the 2.7+ or 3.x versions.

This has been tagged as 2.9.0.

I've required both with this command with no errors or conflicts - `composer global require drush/drush:^8.0 opdavies/drupal-vm-generator:^2.9`.

```
➜  ~ which drush
/Users/opdavies/.composer/vendor/bin/drush
➜  ~ drush --version
 Drush Version   :  8.0.5

➜  ~ which drupalvm
/Users/opdavies/.composer/vendor/bin/drupalvm
➜  ~ drupalvm --version
Drupal VM Generator version 2.9.1
```

Re-running `composer global require opdavies/drupal-vm-generator` should work for you now and install version 2.9.1.

There will be more updates to follow to get it working with the latest stable version of Drupal VM as it's currently a little out of date.
